# Generated by Django 3.2.6 on 2021-08-12 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movieshots_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshots',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieshot', to='movies.movie', verbose_name='Фильм'),
        ),
    ]
