# Generated by Django 3.2.6 on 2021-08-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movieshots_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='movies.Actor', verbose_name='актеры'),
        ),
    ]
